### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by chris48s**
I've written up my notes from our conversation last week while they are still reasonably fresh in my mind and attempted to munge them into the existing README (on top of the changes on your `2017_changes` branch). This has been quite useful as it has forced me to read my notes and the existing docs in detail :)

I _**think**_:

* I've added everything in the right order
* The bits I've deleted/replaced are now out-of-date/inaccurate, based on our conversation

but bear in mind that I am coming at this from the perspective of someone who hasn't actually followed the process in anger, so please sanity-check my edits.

A few questions:

1. I think I've put the "Update `aws.yml`" section in the right place in the sequence, but can you confirm that?

2. I've got some notes on setting `desired_capacity` but this key occurrs under both `Spot price Autoscailing group` and `On-demand Autoscailing group` and I'm not sure what the difference is.

3. I have a note about ensuring the server has at least 4Gb memory due to the `pg_write_heavy.conf` setting `shared_buffers = 4GB` but I can't work out where this is set.

If you can answer those I'll update again with those notes. Thanks

### CODE REVIEW

**Comment by symroe** [comment]
So this looks good to me, but I am also just reading it from memory so we should review this doc when we actually re-deploy next.


Answers: 

1. This is in the wrong place. You edit `aws.yml` _after_ the server image is built, with the API ID of the server image. `aws.yml` then sets up the launch configs for using the correct server image when we bring everything up. See the top of that file for more. I think we should add this to the README directly.

2. I don't know what these two blocks are for. @ashb can you help?

3. It's set in `pg_write_heavy.conf` and that's applied [only when `packer` is defined](https://github.com/DemocracyClub/polling_deploy/blob/2017_changes/provision.yml#L51)

**Comment by ashb** [comment]
Looking

**Comment by ashb** [comment]
If we're talking about the two blocks here:

https://github.com/DemocracyClub/polling_deploy/blob/0e38b22021bf0ea2e25d5b4861aa6fdbd8facad7/aws.yml#L111-L141 (Spot Price)

https://github.com/DemocracyClub/polling_deploy/blob/0e38b22021bf0ea2e25d5b4861aa6fdbd8facad7/aws.yml#L143-L172 (Non spot-price)

Then the spot price one isn't really used most of the time. Spot price is a way of getting an instance for much less (often 10x cheaper) but at the risk that it gets terminated if the bid price goes over what we set/choose. I was using this spot price to test builds and have it cost less when doing so. For production work load we can't rely on Spot Instances as they might be killed out from under us. I was using `ansible-playbook .... -extra-vars=spot_price=0.1` or something similar to get a spot price instance.

**Comment by symroe** [comment]
Excellent, thanks Ash!

**Comment by chris48s** [comment]
OK thanks both :) Have updated based on those comments

**Comment by chris48s** [comment]
Updated with various notes/corrections from yesterday.

**Pull request merged**
